version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb775
    volumes:
      - mongodb_data_container:/data/clashdb
    ports:
      - 27017:27017
    restart: always

volumes:
  mongodb_data_container: