version: "3.8"
services:
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb775
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb775@mongodb:27017
    ports:
      - 8081:8081
    restart: always