version: "3.8"

services:
  megagoal_db_updater:
    image: megagoal_db_updater
    container_name: megagoal_db_updater
    build: .
    env_file:
      - .env
    networks:
      - megagera_network
    volumes:
      - ./logs:/var/log

networks:
  megagera_network:
    external: true

volumes:
  logs: