version: '3.8'

services:
  megagoal_stats:
    image: megagoal_stats
    container_name: megagoal_stats
    build: .
    ports:
      - "8000"
    networks:
      - megagera_network

networks:
  megagera_network:
    external: true

